from pathlib import Path
from .wordDict import wordlist_as_dict
from Scripts.Functions.rotate import rotate_word

path = Path(__file__).parent.parent / 'WordPlay' / 'words.txt'

def rotate_pairs(word, word_dict):
  """Prints all words that can be generated by rotating word.

  word: string
  word_dict: dictionary with words as keys
  """
  for i in range(1,14):
    rotated = rotate_word(word, i)
    if rotated in word_dict:
      print(word, i, rotated)

if __name__ == '__main__':
  fin = open(path)
  word_dict = wordlist_as_dict(fin)

  for word in word_dict:
    rotate_pairs(word, word_dict)


